directories:
  output: appBuild
  buildResources: build
appId: com.n0de.app
productName: N0DE
files:
  - filter:
      - build
      - node_modules
      - Images
      - index.js
      - preload.js
      - apn-client-firebase-adminsdk-orps2-3ab2c5aa16.json
      - .env
extraResources:
  - from: Resources
    to: Resources
    filter:
      - '**/*'
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: appx
      arch:
        - x64
  icon: ./Images/n0de.ico
  requestedExecutionLevel: requireAdministrator
appx:
  identityName: EnigmaIncorporatedLtd.N0DE
  publisher: CN=Enigma Incorporated Ltd
  publisherDisplayName: Enigma Incorporated Ltd
  displayName: N0DE
  applicationId: N0DE
  backgroundColor: '#464646'
  showNameOnTiles: true
  languages:
    - en-US
nsis:
  oneClick: false
  installerIcon: ./Images/n0de.ico
  uninstallerIcon: ./Images/n0de.ico
  uninstallDisplayName: N0DE Uninstaller
  license: license.md
  allowToChangeInstallationDirectory: true
publish:
  provider: github
  owner: Enigma-Incorporated-Ltd
  repo: EnigmaNet-N0DE-Binaries
electronVersion: 30.1.2
