directories:
  output: appBuild
  buildResources: build
appId: com.n0de.app
productName: N0DE
files:
  - filter:
      - build
      - node_modules
      - Images
      - index.js
      - preload.js
      - apn-client-firebase-adminsdk-orps2-3ab2c5aa16.json
      - .env
win:
  target: nsis
  icon: ./Images/n0de.ico
nsis:
  oneClick: false
  installerIcon: ./Images/n0de.ico
  uninstallerIcon: ./Images/n0de.ico
  uninstallDisplayName: N0DE Uninstaller
  license: license.md
  allowToChangeInstallationDirectory: true
publish:
  provider: github
  owner: Enigma-Incorporated-Ltd
  repo: EnigmaNet-N0DE-Binaries
electronVersion: 30.1.2
